sonar.projectKey=bulinrutss_A3-Desempenho-de-compreens-o
sonar.organization=bulinrutss
sonar.projectName=A3 Desempenho de Compreensao

sonar.host.url=https://sonarcloud.io

sonar.java.source=8
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes

sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# Pacotes de interface Swing — difíceis de testar unitariamente
sonar.coverage.exclusions=**/visao/**,**/ControleEstoque.java,**/dao/Conexao.java
